### PR TITLE
Adding add_to_wishlist event

### PR DESCRIPTION
**Pull request by AlexisPPLIN**
Hi !

I've added support for `add_to_wishlist` event.
It's a simple duplication of AddToCartEvent class with few naming changes.

- Google Developers reference for `add_to_wishlist` event :
https://developers.google.com/analytics/devguides/collection/ga4/reference/events?hl=fr&client_type=gtag#add_to_wishlist

Have a nice day  / night !

### CODE REVIEW

**Comment by br33f** [comment]
Thank you for your contribution, however unit test coverage isneeded in order to accept this pull request. 
It'd be also nice if an information about this event would be present in README.md.

**Comment by AlexisPPLIN** [comment]
> however unit test coverage isneeded in order to accept this pull request.
It'd be also nice if an information about this event is present in README.md.

No problem, I've added the needed unit testing and event line in README.md

**Comment by br33f** [comment]
Thank you! It'll be included in version 0.1.4

**Comment by AlexisPPLIN** [comment]
Hi @br33f !
When do you plan to release 0.1.4 ?

Anyway, take your time and have a nice day

**Comment by br33f** [comment]
@AlexisPPLIN Hi,
It is released now :)
https://github.com/br33f/php-GA4-Measurement-Protocol/releases/tag/v0.1.4

**Pull request merged**
